### ISSUE TITLE
MP3 patent issues in some distributions

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/obs-config#3]
How to deal with mp3 support on them (install `libmpg123` or not/just use sdl_mixer instead)?

**Comment by carstene1ns** [comment]
Status update: Currently, users under Debian (+Ubuntu), Fedora and SuSE will not hear MP3 music.

**Comment by Ghabry** [comment]
I thought Debian distributes this in the non-free repo? For Ubuntu this is maybe really a problem because it has a userbase... But Fedora users should be used to it.

**Comment by carstene1ns** [comment]
Sorry, what I wrote was not clear, was just meant as a short summary.
Currently, we do not use `libmpg123` for our OBS builds. That means no mp3 decoder.

Also, as said in #1, the SDL2_mixer build provided by us does not have any external dependencies (~~libmad~~), so it does not support MP3. Usually, this is no problem, as the users will download the newer build from multiverse repository under Ubuntu or default repository under Debian.
However, when they download our build: no MP3 music.

So I need to differentiate my statement from above:
Currently, users under Debian (+Ubuntu) _may not_ and users under Fedora and SuSE _will not_ hear MP3 music.

**About using/building `libmpg123`:**
This is certainly possible, Ubuntu should provide a package and Debian likely too. Depending on which repository it is in, this would need copying over to the OBS. So it can be used for building the Player there.
SuSE and Fedora are a different can of worms, I certainly do not want to deal with their patent policies or void them. However, there are alternative repositories (e.g. [PackMan](http://packman.links2linux.de/)) that also ship mp3 libs. Maybe we can [let them add](https://pmbs.links2linux.de/) a Player build with MP3 support in there.

**Comment by ghost** [comment]
I guess this issue is not a problem anymore, even Fedora and other already added libmpg123 to their repositories.

**Comment by carstene1ns** [comment]
I tried enabling it for 0.5.1, however it is not found under Fedora and SuSE.
I might add it like the SDL stuff as package only for building for Fedora 25+.

**Comment by carstene1ns** [comment]
Fedora 26 comes with MP3 support (17d3d09f2adb).

**Comment by Ghabry** [comment]
Because MP3 patent is gone is this still an issu somewhere?

**Comment by carstene1ns** [comment]
This is now really better:

Arch: has, used
Fedora 28-31, rawhide: has, used
xUbuntu 16.04-18.10: **has not**
xUbuntu 19.04-20.04: has, *unused*
Debian 9: **has not**
Debian 10/Testing: has, *unused*
openSUSE Leap 15.0-15.2, Tumbleweed: has, *unused*

For SUSE it just needs a small .spec update. Debian is a bit more difficult, because the .dsc does not support conditionals.

**Comment by carstene1ns** [comment]
Tumbleweed still has some problem with mp3, but all others former unused have it now enabled.
Edit: Added mp3 support info to README.
